/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/home_office__blender_asset_pack/scene.gltf
Author: Benji Labs (https://sketchfab.com/benjilabs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/home-office-blender-asset-pack-9abf2f407b2945dd9fbdf918ce6e10ff
Title: Home Office | Blender Asset Pack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Model(props) {
  const { nodes, materials } = useGLTF('./models/home_office__blender_asset_pack/scene.gltf')

  // console.log(gltf.current);
  // gltf.current.scene.traverse(function (node) {
  //   // console.log(gltf.scene.children[0].children[0].children[0].children[i]);
  //   console.log(node.ismesh castShadow recieveShadow);
  //   if (node.ismesh castShadow recieveShadow || node.isLight) node.castShadow = true;
  //   if (node.ismesh castShadow recieveShadow || node.isLight) node.receiveShadow = true;

  // }); 
  const ref = useRef()
  const chairRef = useRef()
  console.log(ref.current);
  useFrame(() => {
    // ref.current.rotation.y += 0.001
    chairRef.current.rotation.z += 0.005
  })
  return (
    <group ref={ref}  {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-101.5, 58.95, -98.76]} rotation={[-Math.PI / 2, 0, -0.52]} scale={63.91}>
          <mesh castShadow recieveShadow geometry={nodes.Large_Plant_Plant_Leaf_Shader_0.geometry} material={materials.Plant_Leaf_Shader} />
          <mesh castShadow recieveShadow geometry={nodes.Large_Plant_Pot_Shader_0.geometry} material={materials.Pot_Shader} />
        </group>
        <group position={[-55.64, 92.72, -99.36]} rotation={[-Math.PI / 2, 0, 0.3]} scale={[1.3, 1.3, 0.26]}>
          <mesh castShadow recieveShadow geometry={nodes.Studio_Speaker002_Speaker_Black_0.geometry} material={materials.Speaker_Black} />
          <mesh castShadow recieveShadow geometry={nodes.Studio_Speaker002_Speaker_White_0.geometry} material={materials.Speaker_White} />
        </group>
        <group position={[67.69, 137.12, -122.66]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh castShadow recieveShadow geometry={nodes['Poster_#3_Poster_Border_Black_0'].geometry} material={materials.Poster_Border_Black} />
          <mesh castShadow recieveShadow geometry={nodes['Poster_#3_Poster_White_Border_0'].geometry} material={materials.Poster_White_Border} />
          <mesh castShadow recieveShadow geometry={nodes['Poster_#3_Art_03_0'].geometry} material={materials.Art_03} />
        </group>
        <group position={[-1.03, 137.12, -122.66]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh castShadow recieveShadow geometry={nodes['Poster_#2_Poster_Border_Black_0'].geometry} material={materials.Poster_Border_Black} />
          <mesh castShadow recieveShadow geometry={nodes['Poster_#2_Poster_White_Border_0'].geometry} material={materials.Poster_White_Border} />
          <mesh castShadow recieveShadow geometry={nodes['Poster_#2_Art_01_0'].geometry} material={materials.Art_01} />
        </group>
        <group position={[-70.32, 137.12, -122.66]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh castShadow recieveShadow geometry={nodes['Poster_#1_Poster_Border_Black_0'].geometry} material={materials.Poster_Border_Black} />
          <mesh castShadow recieveShadow geometry={nodes['Poster_#1_Poster_White_Border_0'].geometry} material={materials.Poster_White_Border} />
          <mesh castShadow recieveShadow geometry={nodes['Poster_#1_Art_02_0'].geometry} material={materials.Art_02} />
        </group>
        <group position={[65.31, -1.22, -82.02]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh castShadow recieveShadow geometry={nodes['Desk_#2_Metal_Black_0'].geometry} material={materials.Metal_Black} />
          <mesh castShadow recieveShadow geometry={nodes['Desk_#2_Desk_Oak_0'].geometry} material={materials.Desk_Oak} />
        </group>
        <group position={[126.24, 10.1, -100.13]} rotation={[-Math.PI / 2, 0, 0]} scale={[28.4, 23.83, 1.19]}>
          <mesh castShadow recieveShadow geometry={nodes.Book_Shelf_Desk_Oak_0.geometry} material={materials.Desk_Oak} />
          <mesh castShadow recieveShadow geometry={nodes.Book_Shelf_Metal_Black_0.geometry} material={materials.Metal_Black} />
        </group>
        <group ref={chairRef} position={[8.16, -0.21, -18.5]} rotation={[-1.58, 0, -2.65]} scale={[41.75, 41.75, 35.16]}>
          <mesh castShadow recieveShadow geometry={nodes.Computer_Chair_Black_Plastic_0.geometry} material={materials.Black_Plastic} />
          <mesh castShadow recieveShadow geometry={nodes.Computer_Chair_Chair_Seat_0.geometry} material={materials.Chair_Seat} />
          <mesh castShadow recieveShadow geometry={nodes.Computer_Chair_Chrome_0.geometry} material={materials.Chrome} />
        </group>
        <group position={[-94.06, 0.95, -60.48]} rotation={[-Math.PI / 2, 0, 0]} scale={[12.07, 12.07, 0.78]}>
          <mesh castShadow recieveShadow geometry={nodes.Bin_Bin_Metal_0.geometry} material={materials.Bin_Metal} />
          <mesh castShadow recieveShadow geometry={nodes.Bin_Bin_Shader_0.geometry} material={materials.Bin_Shader} />
        </group>
        <group position={[53.88, 92.44, -99.43]} rotation={[-Math.PI / 2, 0, -0.23]} scale={[1.3, 1.3, 0.26]}>
          <mesh castShadow recieveShadow geometry={nodes.Studio_Speaker_Speaker_Black_0.geometry} material={materials.Speaker_Black} />
          <mesh castShadow recieveShadow geometry={nodes.Studio_Speaker_Speaker_White_0.geometry} material={materials.Speaker_White} />
        </group>
        <group position={[-0.93, 78.53, -103.4]} rotation={[-Math.PI / 2, 0, 0]} scale={102.87}>
          <mesh castShadow recieveShadow geometry={nodes.iMac_Silver_iMac_Grey_Shader_0.geometry} material={materials.iMac_Grey_Shader} />
          <mesh castShadow recieveShadow geometry={nodes.iMac_Silver_iMac_Screen_0.geometry} material={materials.iMac_Screen} />
        </group>
        <group position={[-0.05, 70.16, -103.05]} rotation={[-Math.PI / 2, 0, 0]} scale={[44.24, 9.05, 1.41]}>
          <mesh castShadow recieveShadow geometry={nodes.Monitor_Riser_Desk_Oak_0.geometry} material={materials.Desk_Oak} />
          <mesh castShadow recieveShadow geometry={nodes.Monitor_Riser_Desk_Black_0.geometry} material={materials.Desk_Black} />
        </group>
        <group position={[-10, 71.6, -71.43]} rotation={[-1.53, 0, 0.09]} scale={100}>
          <mesh castShadow recieveShadow geometry={nodes.Keyboard_Keyboard_Keys_0.geometry} material={materials.Keyboard_Keys} />
          <mesh castShadow recieveShadow geometry={nodes.Keyboard_iMac_Grey_Aluminium_0.geometry} material={materials.iMac_Grey_Aluminium} />
          <mesh castShadow recieveShadow geometry={nodes.Keyboard_iMac_White_Glass_0.geometry} material={materials.iMac_White_Glass} />
        </group>
        <group position={[19.13, 71.16, -71.77]} rotation={[-Math.PI / 2, 0, -0.1]} scale={100}>
          <mesh castShadow recieveShadow geometry={nodes.Trackpad_iMac_White_Glass001_0.geometry} material={materials['iMac_White_Glass.001']} />
          <mesh castShadow recieveShadow geometry={nodes.Trackpad_iMac_Grey_Aluminium_0.geometry} material={materials.iMac_Grey_Aluminium} />
        </group>
        <mesh castShadow recieveShadow geometry={nodes.Book051_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[100.98, 50.2, -93.45]} rotation={[Math.PI / 2, 0, 3.12]} scale={106.36} />
        <mesh castShadow recieveShadow geometry={nodes.Book050_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[101.91, 52.96, -94.12]} rotation={[Math.PI / 2, 0, 3.02]} scale={94.95} />
        <mesh castShadow recieveShadow geometry={nodes.Book049_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[101.49, 55.66, -93.45]} rotation={[Math.PI / 2, 0, 2.82]} scale={99.13} />
        <mesh castShadow recieveShadow geometry={nodes.Book048_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[106.09, 125.22, -101.94]} rotation={[Math.PI / 2, 0, 3.03]} scale={112.02} />
        <mesh castShadow recieveShadow geometry={nodes.Book047_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[126.49, 11.09, -87.91]} rotation={[-Math.PI / 2, 1.47, 0]} scale={80.23} />
        <mesh castShadow recieveShadow geometry={nodes.Book046_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[124.23, 11.09, -87.91]} rotation={[-Math.PI / 2, 1.47, 0]} scale={82.59} />
        <mesh castShadow recieveShadow geometry={nodes.Book045_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[121.71, 11.09, -88.58]} rotation={[-Math.PI / 2, 1.47, 0]} scale={105.57} />
        <mesh castShadow recieveShadow geometry={nodes.Book044_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[118.86, 11.09, -87.91]} rotation={[-Math.PI / 2, 1.47, 0]} scale={112.02} />
        <mesh castShadow recieveShadow geometry={nodes.Book043_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[116.06, 11.09, -87.91]} rotation={[-Math.PI / 2, 1.47, 0]} scale={100} />
        <mesh castShadow recieveShadow geometry={nodes.Book042_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[113.25, 11.09, -88.58]} rotation={[-Math.PI / 2, 1.47, 0]} scale={104.4} />
        <mesh castShadow recieveShadow geometry={nodes.Book041_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[110.55, 11.09, -87.91]} rotation={[-Math.PI / 2, 1.47, 0]} scale={94.77} />
        <mesh castShadow recieveShadow geometry={nodes.Book040_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[152.18, 48.78, -90.63]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={112.02} />
        <mesh castShadow recieveShadow geometry={nodes.Book039_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[149.38, 48.78, -90.63]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={100} />
        <mesh castShadow recieveShadow geometry={nodes.Book038_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[146.57, 48.78, -90.63]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={104.4} />
        <mesh castShadow recieveShadow geometry={nodes.Book037_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[143.87, 48.78, -91.53]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={94.77} />
        <mesh castShadow recieveShadow geometry={nodes.Book036_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[141.39, 48.78, -90.63]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={86.01} />
        <mesh castShadow recieveShadow geometry={nodes.Book035_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[139.12, 48.78, -90.63]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={80.23} />
        <mesh castShadow recieveShadow geometry={nodes.Book034_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[136.85, 48.78, -90.63]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={82.59} />
        <mesh castShadow recieveShadow geometry={nodes.Book033_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[134.33, 48.78, -91.53]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={105.57} />
        <mesh castShadow recieveShadow geometry={nodes.Book032_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[131.49, 48.78, -90.63]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={[79.41, 112.02, 112.02]} />
        <mesh castShadow recieveShadow geometry={nodes.Book031_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[128.68, 48.78, -90.63]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={100} />
        <mesh castShadow recieveShadow geometry={nodes.Book030_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[125.88, 48.78, -90.63]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={104.4} />
        <mesh castShadow recieveShadow geometry={nodes.Book029_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[123.18, 48.78, -91.53]} rotation={[Math.PI / 2, 1.53, -3.14]} scale={94.77} />
        <mesh castShadow recieveShadow geometry={nodes.Book025_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[108.07, 11.09, -87.91]} rotation={[-Math.PI / 2, 1.47, 0]} scale={86.01} />
        <mesh castShadow recieveShadow geometry={nodes.Book024_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[105.8, 11.09, -88.58]} rotation={[-Math.PI / 2, 1.47, 0]} scale={80.23} />
        <mesh castShadow recieveShadow geometry={nodes.Book023_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[103.53, 11.09, -87.91]} rotation={[-Math.PI / 2, 1.47, 0]} scale={82.59} />
        <mesh castShadow recieveShadow geometry={nodes.Book022_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[101.01, 11.09, -87.91]} rotation={[-Math.PI / 2, 1.47, 0]} scale={105.57} />
        <mesh castShadow recieveShadow geometry={nodes.Book002_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[107.01, 127.98, -102.61]} rotation={[Math.PI / 2, 0, 2.93]} scale={100} />
        <mesh castShadow recieveShadow geometry={nodes.Book001_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[106.59, 130.81, -101.94]} rotation={[Math.PI / 2, 0, 2.73]} scale={104.4} />
        <mesh castShadow recieveShadow geometry={nodes.Small_Plant_Plant_Shader_0.geometry} material={materials.Plant_Shader} position={[143.8, 123.96, -104.84]} rotation={[-Math.PI / 2, 0, 1.46]} scale={[2.11, 0.97, 2.57]} />
        <mesh castShadow recieveShadow geometry={nodes.Desk_Mat_Mat_Black_0.geometry} material={materials.Mat_Black} position={[-0.51, 70.29, -71.96]} rotation={[-Math.PI / 2, 0, 0]} scale={106.25} />
        <mesh castShadow recieveShadow geometry={nodes.Books_Book_Procedural_Shader_0.geometry} material={materials.Book_Procedural_Shader} position={[118.36, 86.14, -95.41]} rotation={[-Math.PI / 2, -0.01, 0]} scale={94.77} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/home_office__blender_asset_pack/scene.gltf')
